version: '2.2'
services:
  ls01:
    image: docker.elastic.co/logstash/logstash:7.3.1
    container_name: ls01
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./config/:/usr/share/logstash/config/
    ports:
      - 9600:9600
      - 5044:5044
    networks:
      - esnet

networks:
  esnet:
