version: '2.2'
services:
  kb72:
    container_name: kb73
    image: docker.elastic.co/kibana/kibana:7.3.1
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    networks:
      - esnet

networks:
  esnet:
